In [6]:
#NumPyをインポートするコードを記述する
import numpy as np

#AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#行列の積の計算をするコードを記述する
np.dot(A, B)

#Step3.の計算結果を表示するコードを記述する
print(np.dot(A, B))

#行列の要素の最大値を求めるコードを記述する
np.dot(A, B).max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


np.int64(47)